### ISSUE TITLE
add an example

### ISSUE THREAD

**Issue by miguelantonio** [rundeck-plugins/mesos-steps#2]
Hi @carlosrfranco, Fred needs an export of a sample job using this plugin to allocate a new service (PUT) and connect to it, to issue a test command (i.e. whoami, uname, etc)

I think it's valuable, as he is testing this, could you provide that in an "examples" folder?

Thank you in advance!

**Comment by carlosrfranco** [comment]
@miguelantonio , Sory for the delay. I had commited the examples. Please, check it out!

**Comment by miguelantonio** [comment]
Awesome @carlosrfranco thank you

FYI @fellenberger
