### ISSUE TITLE
Provide specific example

### ISSUE THREAD

**Issue by miguelantonio** [rundeck-plugins/mesos-steps#4]
@carlosrfranco so, provided examples worked nice, still, we need something more specific (this is exactly what the client expects)

1- Mesos step to create container (PUT): to Spin up a new Mesos “Service” (aka container), based on some key criteria defined in the job or template concept.
2- Simple ssh & ls step: Connect to the new service/container via ssh and perform work against it 
3- Mesos step to delete container (DELETE): to tear down the container spawned in 1-

**Comment by carlosrfranco** [comment]
Ok, @miguelantonio , I will check it out.
