### ISSUE TITLE
Sample JSON for running service

### ISSUE THREAD

**Issue by fellenberger** [rundeck-plugins/mesos-steps#5]
Here is a example of the JSON for a running service in DC/OS.  This is representative of a service that I would like the Rundeck-Mesos plugin to be able to start up and tear down.

In this particular case, the Service "fellenbe -> rundeck-test-systemd-sshd" has one instance running.  I'd like to better understand how the Mesos step plugin could create a new service "fellenbe -> mesos_test" (1 instance of this service).

It would be great if it was possible to see the JSON that the mesos-step plugin generates as a result of all of the inputs as well.

![mesos_services](https://user-images.githubusercontent.com/10405889/36011739-36f0b29e-0d0e-11e8-94a4-830b9ae62fdf.png)

![mesos_service_fellenbe](https://user-images.githubusercontent.com/10405889/36011742-3b6abd38-0d0e-11e8-8448-209f11fef51e.png)

![mesos_service_fellenbe_instances](https://user-images.githubusercontent.com/10405889/36011744-3ecfe91c-0d0e-11e8-9274-833e2aff28f0.png)

```
{
  "volumes": null,
  "id": "/fellenbe/rundeck-test-systemd-sshd",
  "cmd": null,
  "args": null,
  "user": null,
  "env": null,
  "instances": 1,
  "cpus": 1,
  "mem": 512,
  "disk": 0,
  "gpus": 0,
  "executor": null,
  "constraints": null,
  "fetch": null,
  "storeUrls": null,
  "backoffSeconds": 1,
  "backoffFactor": 1.15,
  "maxLaunchDelaySeconds": 3600,
  "container": {
    "docker": {
      "image": "docker.optum.com/dms/centos:7-systemd-sshd",
      "forcePullImage": true,
      "privileged": true,
      "portMappings": [
        {
          "containerPort": 22,
          "protocol": "tcp",
          "servicePort": 10117,
          "labels": {
            "VIP_0": "/fellenbe/rundeck-test-systemd-sshd:22"
          }
        }
      ],
      "network": "BRIDGE"
    }
  },
  "healthChecks": [
    {
      "protocol": "TCP",
      "gracePeriodSeconds": 10,
      "intervalSeconds": 30,
      "timeoutSeconds": 5,
      "maxConsecutiveFailures": 5,
      "port": 22
    }
  ],
  "readinessChecks": null,
  "dependencies": null,
  "upgradeStrategy": {
    "minimumHealthCapacity": 1,
    "maximumOverCapacity": 1
  },
  "labels": null,
  "acceptedResourceRoles": null,
  "residency": null,
  "secrets": null,
  "taskKillGracePeriodSeconds": null,
  "portDefinitions": [
    {
      "port": 10117,
      "protocol": "tcp",
      "labels": {}
    }
  ],
  "requirePorts": false
}
```

**Comment by fellenberger** [comment]
For example, I'm not seeing where one specifies the docker image to use to instantiate the new service via the Mesos Step plugin.  Looking forward to discussing this further to better understand how this works.

**Comment by carlosrfranco** [comment]
I did the push with some change in mesos plugin. The operation is simple, being necessary only to insert the data that has the same names as in json of the example presented by the client.
For fields that have more complex data, you need to include a json that represents it. (For example, the "container" field).
In this screenshot, they are filled with the same data as the client example. I am also sending an xml of the exported job...


![mesos_put_app_step](https://user-images.githubusercontent.com/7209908/36113336-9e1cdc7e-1013-11e8-88ae-1d92df915921.png)


[Teste_Job_Client_Example.xml.zip](https://github.com/rundeck-plugins/mesos-steps/files/1717362/Teste_Job_Client_Example.xml.zip)
